### ISSUE TITLE
Profiler doesn't connect

### ISSUE THREAD

**Issue by davidich** [PrivateEye/PrivateEye#2]
I did start listening in F#, never receive profiler connected when running profiler in Windows10 (x64).
What should I do?

**Comment by sawilde** [comment]
Sorry to hear that, can you detail your steps?

**Comment by gregoryyoung** [comment]
The solution was upgrade to 4.6

On Sun, Jul 10, 2016 at 12:17 PM, Shaun Wilde notifications@github.com
wrote:

> Sorry to hear that, can you detail your steps?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/PrivateEye/PrivateEye/issues/2#issuecomment-231579186,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAXRWmRSMa6hJwFZ8LcvOZ3hGybJ0eTAks5qULi0gaJpZM4JIOQN
> .

## 

Studying for the Turing test

**Comment by sawilde** [comment]
> The solution was upgrade to 4.6

perhaps but that does not make sense

**Comment by gregoryyoung** [comment]
I agree. There likely was something else going on but I don't have more
details. Perhaps @davidich has some?

On Mon, Jul 11, 2016 at 6:03 AM, Shaun Wilde notifications@github.com
wrote:

> The solution was upgrade to 4.6
> 
> perhaps but that does not make sense
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/PrivateEye/PrivateEye/issues/2#issuecomment-231632571,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAXRWoD8NrfPD6xgvW_tRFKTBcaV50O3ks5qUbKOgaJpZM4JIOQN
> .

## 

Studying for the Turing test

**Comment by davidich** [comment]
The reason @gregoryyoung replied with a wrong solution is my fault. One guy at BuildStuff conf told me he had had similar to my problem issue and he had solved it by changing .net version. I simply believed him, didn't check it myself  and told that solution to Greg.
In my case the problem was in "prefer 32 bit option" set in project properties and either running via "launchapp32.cmd" or unchecking this option solved the problem.
Sorry for not reading "windows_readme" as it describes my root of cause.

**Comment by sawilde** [comment]
> In my case the problem was in "prefer 32 bit option" set in project properties

no worries, I suspected that might be the case - glad you got it running.
