### ISSUE TITLE
Push the code

### ISSUE THREAD

**Issue by adamralph** [PrivateEye/PrivateEye#3]
I only see .gitignore, LICENSE (MIT) and a README.md.

The choice of license, and seeing this on the http://www.privateeye.io/

![image](https://cloud.githubusercontent.com/assets/677704/18814424/23fdb596-8313-11e6-8be2-5c8186f3fad5.png)

suggests that there should be some code here.

Is this indeed an open source product or do I misunderstand?

**Comment by gregoryyoung** [comment]
We will likely open source the C#/F# side of things but not the C/C++ side of things (there are two pieces to it).
